runtime: nodejs20

handlers:
  - url: /(.*\..+)$ 
    static_files: dist/quoter/browser/\1
    upload: dist/quoter/(.*\..+)$

  - url: /.*
    secure: always
    static_files: dist/quoter/browser/index.html
    upload: dist/quoter/index.html


